### ISSUE TITLE
Lock system does not converge.

### ISSUE THREAD

**Issue by NicolaDes** [NicolaDes/ariadneExample#1]
After 50 second of simulation the system does not evolute.
The problem probably is on file [Controller.hh](https://github.com/NicolaDes/ariadneExample/blob/aziz/lock_system/modules/controllers.hh).

**Comment by lgeretti** [comment]
The lines

``
controller.new_forced_transition(e_a2_close, on_second, out_lock, z2_geq_hmax2);
controller.new_forced_transition(e_a2_close, out_lock, on_first, z2_leq_hmin2);
``

in the controller do not seem right to me: you use the same event for two consecutive transitions. It is not illegal and it does not cause any trouble since the event is not an input event for any other automaton, but it may be an after-effect of some modelling error on your part. 

Please check and tell me if everything is in order.

**Comment by darioemb** [comment]
we reimplemeted the controller of the lock_system as shown in the repository([proportional](https://github.com/NicolaDes/ariadneExample/blob/master/lock_system/modules/controllers.hh)), but we have noticed some prolems:
- In the stabilization phase the system it's stuck, therefore avoiding this phase the system converge but many trajectories are generated, so we suppose the manner of stucking is due to the computation of the trajectories.
Below the execution avoiding the stabilization phase.
![photo6024111496214195273](https://user-images.githubusercontent.com/30407873/39810128-2d419346-5384-11e8-9444-1ac17578bd3d.jpg)
There is a workaround to make ariadne compute less trajectories.

**Comment by lgeretti** [comment]
I noticed that using the default step size (0.5) the set radius grows too quickly. I tried with 0.1 and the evolution completed rather quickly. Please verify that the behavior is the desired one.

**Comment by lgeretti** [comment]
By the way, using 0.1 only one trajectory is present and the result is clean:

![upper_reach 0 1](https://user-images.githubusercontent.com/1506092/40233479-76ce86ba-5aa3-11e8-9984-a950847e2c05.png)

**Comment by darioemb** [comment]
Thank you we obtain the expected results.
Everything works like a charm.
